- hosts: workstation
  gather_facts: false
  tasks:
    - name: Fetch instance information
      os_server_info:
        cloud: openstack
        region_name: regionOne
      register: r_os_servers

    - name: Add in memory hosts to inventory
      add_host:
        name: "{{ item.public_v4 }}"
        ansible_user: cloud-user
        group:
           - "{{ item.metadata.group }}"
           - "{{ item.metadata.deployment_name }}"
      loop: "{{ r_os_servers.openstack_servers }}"