- hosts: localhost
  gather_facts: false
  roles:
  - name: osp-facts

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - name: base-config
    - name: db-tier

# Setup application servers tier

- name: setup app tier
  hosts: apps[1]
  become: yes
  gather_facts: false
  roles:
    - name: base-config
    - name: app-tier

# Setup front-end load balancer tier


- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - name: base-config
    - name: lb-tier



